[package]
name = "component_host_alpha"
language = "1.9"

[build]
module_paths = ["src"]

[component]
abi = 1
identity = "org.chtholly.examples.component-host.alpha"
exports = ["plugin::hold", "plugin::process"]
