add_subdirectory(chthollyc)
add_subdirectory(chthollyc-launcher)
add_subdirectory(chtholly-lsp)
add_subdirectory(chtholly-registryd)
add_subdirectory(chtholly-registry-signer)
add_subdirectory(chtholly-registry-witnessd)
add_subdirectory(chtholly-toolchain)
add_subdirectory(chtholly-test)
add_subdirectory(chtholly-cffi)
add_subdirectory(chtholly-component-deploy)
